eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10  # Gửi heartbeat mỗi 3 giây
    lease-expiration-duration-in-seconds: 10  # Thời gian chờ trước khi xóa instance nếu không nhận được heartbeat
    health-check-url-path: /actuator/health  # Endpoint kiểm tra sức khỏe
    prefer-ip-address: true
    
spring:
  cloud:
    loadbalancer:
      health-check:
        interval: 3s  # Khoảng thời gian kiểm tra sức khỏe

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework.web: DEBUG
