server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  boot:
    message: "Hello from Product Service!"

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework.web: DEBUG
